### ISSUE TITLE
Please make it possible to translate "B.C."

### ISSUE THREAD

**Issue by Webjorn** [NUKnightLab/TimelineJS#427]
Please make it possible to translate "B.C." via the locale language files.

**Comment by sbonaventure** [comment]
+1

**Comment by JoeGermuska** [comment]
I'm afraid this is unlikely to be changed in the current version of Timeline, but I agree that it's important. We hope to release a rewrite of TimelineJS3 in the next few months and this is logged as an issue there (see above).
