### ISSUE TITLE
Custom Thumbnail option only work if media is populated

### ISSUE THREAD

**Issue by Schyzophrenic** [NUKnightLab/TimelineJS#446]
If you have : 
```json
"asset":
    {
        "media": "",
	"credit":"",
	"caption":"",
	"thumbnail": "/myPic.png"
    }
```

then the thumbnail is not taken into account. 
Adding anything in "media" makes the thumbnail to be displayed.

**Comment by lukerague** [comment]
Not sure when this was implemented, but thumbnails now display regardless of main media presence.
