### ISSUE TITLE
HTTPS issue, https://mydomain/timeline.htm not showmy the content, excet title of the page.  

### ISSUE THREAD

**Issue by anirbanc** [NUKnightLab/TimelineJS#485]
I have hosted on my server, and calling through http, it is working like charm. 

But when i calling it through https://( Through secure connection) it is hiving me blank page. 

IN THE FIREFOX IT IS GIVING MY WARNING THAT " FIREFOX BLOCKING SOME CONTENT WHICH IS NOT SECURE"

AND OTHER BROWSER NOT EVEN GIVING ME THIS WARRING EXCEPT A BLANK WHITE PAGE.

It will be great help , if you please help me to call this timeline over secure connection.

Thanks
Anirban Choudhury

**Comment by lukerague** [comment]
This response is super late, because this question was been answered elsewhere shortly after. But in case people find this and not where it is answered: https://knightlab.zendesk.com/entries/28095618-Trouble-embedding-into-HTTPS
