### ISSUE TITLE
Calendars and Month Names

### ISSUE THREAD

**Issue by milnerm** [NUKnightLab/TimelineJS#486]
I'm using this for building historical timelines for university classrooms, and I've got it working with AJAX pulling from a MYSQL DB to filter by tags, as well as limit the start / stop of the calendar, and to use Julian, Gregorian, and Jewish dates. The only thing at the moment is that the array of month names in timeline.js is in English, and is for Christian calendars. I've added an additional field to the returned JSON that indicates the calendar used in rendering the JSON (all the cross calendrical magic is handled before json_encode in PHP), but I'd like to be able to choose not only the language, but the actual Hebrew calendar. Right now picking the language simply makes a gregorian date in Hebrew (ie נובמבר is november): I want the months like Kislev and Adar. I've got them as integers, it's the array in timeline.js on lines 1239-1240 that are the problem. 

Because storyjs-embed.js is minified, I can't actually fork effectively and offer up the code for folks......

**Comment by lukerague** [comment]
Hello, and sorry for the super later response.

So things have obviously changed a lot since this question was asked, and we have a non-minified version that builds next to the minified version. Forking it and offering a Hebrew calendar should be much easier now.

**Comment by elrodro83** [comment]
I just made a change that may allow to put the calendar you want: https://github.com/NUKnightLab/TimelineJS/pull/804

The missing part would be to hook it up with a library that gebnerates the proper hebrew dates based on the Date object (tehe timestamp, essentially).
