### ISSUE TITLE
Mixed Content Warnings / Blocked

### ISSUE THREAD

**Issue by cmcavoy** [NUKnightLab/TimelineJS#493]
If I serve Timeline.js from a https domain, some of the included resources are served as http (firing mixed content warnings, and in some browsers blocking the content). If I mark all my spreadsheet assets as https, Timeline still pulls in http versions of some resources (like the Vimeo player).

I've been playing around with it here: https://cmcavoy.makes.org/thimble/a-timeline-js-example

**Comment by JoeGermuska** [comment]
A number of changes have been made which should address this. Obviously almost two years later you may no longer care that much. The given URL doesn't work but that may be other bitrot at work

**Comment by cmcavoy** [comment]
hi @JoeGermuska!
