### ISSUE TITLE
What is the proper way of compile modified source?

### ISSUE THREAD

**Issue by akfish** [NUKnightLab/TimelineJS#494]
Hi, I am reading the code and planing to add some features.
I notice that files in ```compiled``` folder seems to be generated from the ones in ```source```. But I couldn't find any documentations on what tool chain is used and how to properly do it. 
And I noticed that some pull requests are making changes to ```source``` while the others are making changes to ```compiled```.  
So I was hoping for some clarification on these issues. Thanks.

**Comment by lukerague** [comment]
We only accept pull requests with changes to the source folder, as compiled and build are overwritten by our own compiling programs. For your own testing environment, you can use any compiling program. I use http://koala-app.com/, but there are many out there.

**Comment by JoeGermuska** [comment]
Actually, to clarify: `compiled` represents working files from @zachwise's development process. They are the result of compiling with [Codekit](https://incident57.com/codekit/), and Codekit users will recognize the configuration for including file fragments, etc.

Those files are not used for ongoing development. Rather, a python-based build process has been created which leverages the same Codekit configuration to prepare files and put them in the `build` directory.  Information about working with this toolkit is documented in [DEVELOPER.md](https://github.com/NUKnightLab/TimelineJS/blob/master/DEVELOPER.md).

Of course, this original ticket is pretty old, but should anyone catch up with this and be interested, this is another time to point out that forward development of TimelineJS is happening in a [new codebase](http://github.com/NUKnightLab/TimelineJS3). It is still in a prerelease state, but no major new features will be added to the version in this repository.
