### ISSUE TITLE
Change class names to be plugin specific + remove Javascript styling.

### ISSUE THREAD

**Issue by aaronbauman** [NUKnightLab/TimelineJS#495]
Reopening https://github.com/VeriteCo/TimelineJS/issues/254

As far as I can seem, javascript-styling and container selectors have not changed significantly.

There are too many examples to list exhaustively.
For example, this entire section from timeline.js:
```javascript
VMM.Lib.css(".slider-item .layout-text-media .text", "width", "40%" );
VMM.Lib.css(".slider-item .layout-text-media .text", "display", "table-cell" );
VMM.Lib.css(".slider-item .layout-text-media .text .container", "display", "table-cell" );
VMM.Lib.css(".slider-item .layout-text-media .text .container", "width", "auto" );
VMM.Lib.css(".slider-item .layout-text-media .text .container .start", "width", mediasize.text_media.text.width );
//VMM.Lib.addClass(".slider-item .content-container", "pad-left");
VMM.Lib.removeClass(".slider-item .content-container", "pad-top");

VMM.Lib.css(".slider-item .layout-text-media .media", "float", "left" );
VMM.Lib.css(".slider-item .layout-text-media", "display", "table" );

VMM.Lib.css(".slider-item .media blockquote p", "line-height", "36px" );
VMM.Lib.css(".slider-item .media blockquote p", "font-size", "28px" );

VMM.Lib.css(".slider-item", "display", "table" );
VMM.Lib.css(".slider-item", "overflow-y", "auto" );
```

**Comment by lukerague** [comment]
Zach didn't give a reason as to why the last issue was closed, but there is one. By the time it was realized our class names were too non-specific, it was too late. Fixing it would break most, if not all, of the existing customized Timelines. We are currently developing a new version where all class names are Timeline specific.

As for the JavaScript styling, in the current version it is to a minimum. For Timeline3, there is a resurgence (in non-jQuery form), but the majority of them are handling dynamic widths and heights. If you have suggestions for how to get rid of some of them, we are all ears: https://github.com/NUKnightLab/TimelineJS3

**Comment by aaronbauman** [comment]
Thank you for the followup.
I will check out the new project.
