### ISSUE TITLE
Please document availability of https hosted version (S3)

### ISSUE THREAD

**Issue by technotarek** [NUKnightLab/TimelineJS#508]
I needed to serve your hosted version on an https enabled page. I thought I was out of luck until I accidentally stumbled upon this src URL in your code:

https://s3.amazonaws.com/cdn.knightlab.com/libs/timeline/latest/embed/index.html?

Please document this point!

Great plugin. Thanks in advance.

**Comment by JoeGermuska** [comment]
As of now, cdn.knightlab.com can be accessed via SSL and URLs no longer need to be changed.
