### ISSUE TITLE
Using only the timeline's navigation 

### ISSUE THREAD

**Issue by Urigo** [NUKnightLab/TimelineJS#513]
Hi guys,
Very nice work!
I want to use only the navigation (everything inside "vco-navigation") and nothing from "vco-feature".
Is there a simple and elegant way to do so?
Thanks!

**Comment by arunslb123** [comment]
Hi, How to add hyper link in the time line part. I don't want the upper part, so i disabled as per your trick. I just want to make a link on timeline entries. When user click that link, it will open a new page. How to do this? help
