### ISSUE TITLE
Non-linear timeline

### ISSUE THREAD

**Issue by AndyRead** [NUKnightLab/TimelineJS#665]
Have there been any thoughts on having a non-linear timeline?  I'm working on a project, which might be quite typical, where an organisation has historic events going back to a few dates in the 17th C, 19th C, early 20th C, but then lots of events clustered around the last few years. A non-linear timeline would allow recent events to be more spaced out while ancient events would come closer together.  There are various options for mathematically defining the actual non-linear curve.

**Comment by evanwolf** [comment]
+1. People will only scroll so many times through empty time spans before quitting. You have two or three swipes to show something new, or to introduce a teaser or a way to easily jump to the next cluster.

**Comment by JoeGermuska** [comment]
This isn't a priority for us. Also, major feature development will not happen in this repository. We are moving development to the [TimelineJS3](https://github.com/NUKnightLab/TimelineJS3) project.

Our hope is that the code in that project is better organized to support community contributions. If this is something you're interested in, you might take a look to see how you might implement an alternative positioning algorithm. We'd definitely review a pull request which supported this, as long as it doesn't make TimelineJS unduly complicated for otehr users.
