### ISSUE TITLE
Issue with Internet Explorer and UTC time

### ISSUE THREAD

**Issue by Raythekool** [NUKnightLab/TimelineJS#668]
Hi all,
I've encountered a little problem in this fantastic Timeline.
When i use a DateTime string in UTC to populate the startDate/endDate property of the JSON object of the timeline (i.e. to display appointments with their start date and time) in Internet Explorer (tested on versions 8, 9 and 10) it does not convert the time to my current timezone.
This should not be an issue itself, except that on Chrome the timezone is correctly applied.
The result is that, whichever date time format I use (i.e.: "2013-06-07T15:30:00.000Z"), on I.E. and Chrome I see 2 different hours for the same appointment.
Am I making some mistake or is there really an issue?
Many thanks and congratulations again!

**Comment by JoeGermuska** [comment]
closing on account of extreme age
