### ISSUE TITLE
Uncaught TypeError: Cannot read property 'styleSheets' of undefined

### ISSUE THREAD

**Issue by binarykitchen** [NUKnightLab/TimelineJS#729]
This happens when I require TimelineJS from Browserify and load the bundled JS file in any browser.

For now I can think of a temporary bugfix like this at line 2632

```js
})(this.document || document);
```

**Comment by cweems** [comment]
@JoeGermuska also having this issue with an implementation of timelinejs. Will post any solutions that I find here.

**Comment by JoeGermuska** [comment]
This version of TimelineJS is no longer under active development. We are focused on developing [TimelineJS3](https://github.com/NUKnightLab/TimelineJS3) as a successor. That said, we have not yet invested energy in configuring TimelineJS3 for Bower or other dependency management. Contributions (pull requests) would be welcome.

jQuery will not be a dependency for TimelineJS3.

**Comment by gruebait** [comment]
Same issue on plain vanilla Node as well as Electron. Looks like there is currently no way to run either version of TL (2 or 3) when installed via a PM?

**Comment by earmstrong1990** [comment]
@gruebait What tweaks did you make?  I'm also using Node and Electron and am getting this issue
