### ISSUE TITLE
net::ERR_ADDRESS_UNREACHABLE

### ISSUE THREAD

**Issue by t1gor** [NUKnightLab/TimelineJS#742]
In chome, when the YouTube API is trying to init, it seems that it tries to load or trigger events for Chrome Cast plugin, even if it is not installed, so for every video in I get an error in console:

```
GET chrome-extension://boadgeojelhgndaghljhdicfkmllpafd/cast_sender.js net::ERR_FAILED
```

Which is pretty annoying.

I've tried googling this error, but there seems to be no solution so far. Maybe, we could use an older version of YouTube API? Like 2.0, for example ...

https://developers.google.com/youtube/code

Hope this helps.

**Comment by CFXd** [comment]
This is an unfortunate issue I encountered too. I found more info here: http://stackoverflow.com/questions/24490323/google-chrome-cast-sender-error-if-chrome-cast-extension-is-not-installed-or-usi

**Comment by JoeGermuska** [comment]
Thanks @CFXd for the information. Closing as this is not specific to Timeline or anything we can do anything about.
