### ISSUE TITLE
Shitty feedback on support forums

### ISSUE THREAD

**Issue by bjcullinan** [NUKnightLab/TimelineJS#753]
I will never use or recommend your plugin to anyone.  I have come across many threads that instead of providing a solution, close the ticket with "we are not implementing it because timelinejs is meant to tell a story".  Here is the perfect example:
https://groups.google.com/forum/#!topic/verite-timeline/988FbNqm59w

I don't know who Jeff David is, but the person wanted an answer on HOW TO AUGMENT THE FUCKING CODE!  Lay off the caps douche bag.

I wish I had found vis.js before wasting hours trying to implement your poorly documented library.
http://visjs.org/docs/timeline.html

**Comment by JoeGermuska** [comment]
Github issues are not a place to vent your frustration. If you have a product you prefer, then we are happy that you have found it. There's no need to post antagonistic GitHub issues.

**Comment by bjcullinan** [comment]
Apparently it isn't a place to get help on your project either.

**Comment by JoeGermuska** [comment]
No, it isn't. We ask that people who need help with TimelineJS use our Zendesk system: http://knightlab.zendesk.com, or email to support@knightlab.zendesk.com
