### ISSUE TITLE
IDs are different by browser

### ISSUE THREAD

**Issue by lukerague** [NUKnightLab/TimelineJS#760]
As per support ticket 1000 (woooo!), events with the same start date are not given the same slide number in every browser when the timeline is locally hosted and embedded inline.

I.e - http://meridiano-6.com/personajes-moderna/#7 will take you to Shakespeare in some browsers and Galileo in others. 

The user had a decent suggestion: "It would be great that you can manually set the anchor or ID for every element in the timeline since you could add extra elements and the url of the previous elements could change (for instance if you add a element before an already existing event)."

**Comment by JoeGermuska** [comment]
Manual IDs as well as consistent event sorting are features in [TimelineJS3](http://timeline3.knightlab.com). It's exactly the kind of thing that was too hard to sort out changing in the current version without impacting compatibility, etc.

So unfortunately, this isn't something we can fix in the current Timeline.

**Comment by lukerague** [comment]
Alright, I'll pass that along.
