### ISSUE TITLE
server.py in repo

### ISSUE THREAD

**Issue by lukerague** [NUKnightLab/TimelineJS#761]
Another suggestion via a support ticket (#1002):

"Consider to place a server.py in the repository with content:

import SimpleHTTPServer 
import SocketServer 
PORT = 8000 
Handler = SimpleHTTPServer.SimpleHTTPRequestHandler 
httpd = SocketServer.TCPServer(("", PORT), Handler) 
print "serving at port", PORT 
httpd.serve_forever()

There is a suggestion in the readme file to use `python -m SimpleHTTPServer 8000`. But if there is a server.py in the repo, the server can be started right in a developer environment."

I don't know enough about this to rule on its usefulness.

**Comment by acdha** [comment]
Are there plans to customize the server in some way? If not, it generally seems like a bad idea to put developer-specific code in a repo to replace a one-line shell command with no third-party dependencies.

**Comment by JoeGermuska** [comment]
I don't think we'll do this. Agreed with @acdha that no gain is added by this server.py. Also, while our local server strategy (`fab runserver`) is idiosyncratic to some, if someone really is trying to do Timeline development, it would be best to make that work rather than adding something new.
