### ISSUE TITLE
load events in chunks

### ISSUE THREAD

**Issue by Hinnack** [NUKnightLab/TimelineJS#764]
this is a duplicate of #180 but no one reopened that. so please reopen #180 or leave this.

This is useful if you have thousands of events. It would not only speed up loading, as the amount of data is much smaller, but the producement of data (json) would be faster, too. In both cases the timeline would load much faster.
The easiest way to implement may be having a next_chunk_url in the JSON like Facebook does, where the next chunk of data would be loaded and added to the array of dates until no next_chunk_url given.

**Comment by JoeGermuska** [comment]
A feature of this scope will not be added to this codebase of TimelineJS. 

We are [rewriting TimelineJS](https://github.com/NUKnightLab/TimelineJS3) with a projected initial release this spring. One of the goals is to provide better organized/factored code to support community code contributions and better maintainability in general.

I will point out that TimelineJS is very deliberately designed for story telling, so Knight Lab is unlikely to invest effort in features which are not narrative (and there's no way a 1000+ event timeline is predominantly narrative.) However, we do want to support community contributions, so a pull request which has no impact on using TimelineJS for it's primary feature but which serves other goals might be accepted.

Alternatively, there may be other tools which are less opinionated that serve your purpose. The VisJS library has a [timeline component](http://visjs.org/timeline_examples.html) which might be worth a look.
