### ISSUE TITLE
Loading a custom CSS file part 2

### ISSUE THREAD

**Issue by kathep** [NUKnightLab/TimelineJS#771]
Hi all

I have downloaded the zip and edited the css for the timeline. I know the CSS changes work, as I have tested them in the browser Element Inspector. 

I have changed the css references in the HTML and JS files to point to my updated, local CSS file, but the live version of the timeline keeps pulling css from the knightlab servers.

Does anyone know why this might be, and/or how I can change it?

**Comment by kathep** [comment]
The CSS is being loaded from the knightlab servers via a lazyload function, and appears below my custom css, therefore overwriting my changes. Please help!

**Comment by lukerague** [comment]
Hi! I'm happy to help. Can I see the embed code or function call you're using?

**Comment by kathep** [comment]
Hi @lukerague!

Here is the latest embed code I'm using...

'	<div id="timeline-embed"></div>
	<script type="text/javascript">
	    var timeline_config = {
			width:				'100%',
			height:				'600',
			source:				'https://docs.google.com/spreadsheet/pub?key=0At_x8atSeVqEdHlTSGw1VzFTaklBSHVLNmFTOGd6c0E&output=html',
			embed_id:			'timeline-embed',				//OPTIONAL USE A DIFFERENT DIV ID FOR EMBED
			start_zoom_adjust:	'3',							//OPTIONAL TWEAK THE DEFAULT ZOOM LEVEL
			hash_bookmark:		true,							//OPTIONAL LOCATION BAR HASHES
			font:				'Bevan-PotanoSans',				//OPTIONAL FONT
			debug:				true,							//OPTIONAL DEBUG TO CONSOLE
			maptype:			'watercolor',					//OPTIONAL MAP STYLE
			css:				'TimelineJS-master/build/css/timeline.css',		//OPTIONAL PATH TO CSS
		}
	</script>
	<script type="text/javascript" src="http://cdn.knightlab.com/libs/timeline/latest/js/storyjs-embed.js"></script>'

Apologies for the *terrible* code formatting. 

![screenshot 2015-03-12 08 12 45](https://cloud.githubusercontent.com/assets/7587390/6620738/9c30032e-c88f-11e4-9df7-abfc2b469206.png)
This is my problem.... css drawing from knightlab.

**Comment by lukerague** [comment]
I'm not seeing the embed code, try again?

**Comment by kathep** [comment]
The first block of code I pasted is the embed code, right? Or are you looking for iframe code?

**Comment by kathep** [comment]
This is what I see, using that code...
![screenshot 2015-03-12 08 20 07](https://cloud.githubusercontent.com/assets/7587390/6620899/a90438d0-c890-11e4-95e3-deceeb0adc65.png)

**Comment by kathep** [comment]
I got this code from the 'build' folder of the TimelineJS zip. Is there different code I should be using?

**Comment by lukerague** [comment]
I'm sorry, you were fine! We are dealing with slow internet and the code didn't show at first, it was just an empty box. The build folder is exactly what you need. You're not using an iframe embed as well, correct?

**Comment by kathep** [comment]
No, no iframe embed.

**Comment by kathep** [comment]
The problem seems to be this lazyloaded code in the header...
![screenshot 2015-03-12 08 18 01](https://cloud.githubusercontent.com/assets/7587390/6621403/a43f3e32-c893-11e4-9857-c062fffe1065.png)

But I haven't figured out how to get rid of the lazyloaded css without messing up the timeline.

**Comment by lukerague** [comment]
Sorry for the radio silence. I have a work around, and also a question.

First the work around. If you're only changing the CSS, we have another method of pulling in an external style sheet. Follow this template:

<iframe src='http://cdn.knightlab.com/libs/timeline/latest/embed/index.html?source=10fFZXg4kioMz8uTVDZfawiJkgrWZxfJuziK1i1AaCrs&css=http://www.lukerague.com/css/timeline.css&js=http://cdn.knightlab.com/libs/timeline/latest/js/timeline.js&font=Bevan-PotanoSans&maptype=toner&lang=en&height=650' width='100%' height='650' frameborder='0'></iframe>

Replace the source= with your spreadsheet's ID, and the css= with the full URL for your CSS stylesheet. And you change change all of the other options of course. I just tested this method and it should work correctly.

And now the question. In your screen shot, it is pulling in custom stylesheet as the very first stylesheet. Does it pull it in at all if you don't manually add it to the head? If not, the problem might not be an issue with the lazyload, but with how the JS builds out of the inline method.

**Comment by kathep** [comment]
Hey Luke!

Thanks for getting back to me. I just tested removing the stylesheet link the header - without it, my custom css file doesn't load.

The suggested workaround is unfortunately exactly what I am doing in the code I posted yesterday. 

![screenshot 2015-03-13 10 33 21](https://cloud.githubusercontent.com/assets/7587390/6643845/d813d284-c96c-11e4-8555-c36dee3d44ea.png)

The problem is that the css from the knightlab server is being pulled in under my custom style sheet, therefore overriding the settings in my modified style sheet.  

I have been messing around with the js file to try to get this to work. Perhaps I have broken something?

**Comment by kathep** [comment]
UPDATE: Sorry, the old code is not the full url. I updated the line marked 'custom css' above to the full url this morning, without any change in the result.

**Comment by lukerague** [comment]
Wait, my code didn't make it in. This is what I was trying to show you (it's an iframe instead of an inline)

`<iframe src='http://cdn.knightlab.com/libs/timeline/latest/embed/index.html?source=10fFZXg4kioMz8uTVDZfawiJkgrWZxfJuziK1i1AaCrs&css=http://example.com/css/timeline.css&js=http://cdn.knightlab.com/libs/timeline/latest/js/timeline-min.js&font=Bevan-PotanoSans&maptype=toner&lang=en&height=650' width='100%' height='650' frameborder='0'></iframe>`

**Comment by kathep** [comment]
Hey Luke

Thanks for the code. I just tried it - the timeline shows, but my custom css file doesn't even load.

Any other ideas?

**Comment by lukerague** [comment]
Using this:

`<iframe src='http://cdn.knightlab.com/libs/timeline/latest/embed/index.html?source=10fFZXg4kioMz8uTVDZfawiJkgrWZxfJuziK1i1AaCrs&css=http://kathep.com/tests/07_research_timeline/TimelineJS-master/build/css/timeline.css&js=http://cdn.knightlab.com/libs/timeline/latest/js/timeline-min.js&font=Bevan-PotanoSans&maptype=toner&lang=en&height=650' width='100%' height='650' frameborder='0'></iframe>`

I'm able to load a test Timeline with your CSS stylesheet, with no interference from the main CSS stylesheet.

![screenshot 106](https://cloud.githubusercontent.com/assets/7632315/6645785/59fef812-c98d-11e4-92ea-91fdde47fba6.png)

**Comment by kathep** [comment]
Ah, thank you! There must have been some operator error in my previous test. :)

Thank you for your help, Luke.

**Comment by kathep** [comment]
Ah, Luke, I have some bad news for you... the knightlab css is *still* being loaded after my css file. After initial FTP transfer, it doesn't show up, but as soon as I start inspecting elements, it shows up! See below...

![screenshot 2015-03-13 16 34 33](https://cloud.githubusercontent.com/assets/7587390/6649036/397e7650-c99f-11e4-84a2-49d16ff02329.png)

Could this be the problem with the js file you mentioned earlier in this thread?

**Comment by kathep** [comment]
This view shows how the knightlab server css file doesn't show up in the inspector initially (left side of inspector), but the inspector also shows that the knightlab server css file is controlling elements on my page (yellow tooltip on right side of inspector). Very strange behavior!

![screenshot 2015-03-13 16 42 43](https://cloud.githubusercontent.com/assets/7587390/6649094/30fd23ea-c9a0-11e4-8d13-cde71eae2648.png)

Can you help?

**Comment by lukerague** [comment]
I'm not having the same problem with the embed I gave you, testing in Chrome, Firefox and IE11: 
![screenshot 107](https://cloud.githubusercontent.com/assets/7632315/6670298/d56c1de6-cbcb-11e4-89f8-8f0382a44017.png)

My guess is that one of two things is happening. Either the main CSS is still in your browser cache and will go away if you clear the cache, or you have more code on the page that is mucking it up. Is this the only timeline-related code on the page you're testing?

**Comment by kathep** [comment]
Hey Luke

Nope, no other timeline code on the page. I just cleared my browser cache and am getting *exactly* the same behavior.

I know my css file loads - this is not the issue. The issue is that knightlab server css loads below my code via lazyload, hence overwriting every change I try to make. 

This is a good tool for journalists who don't know or want to know css, but it is not helpful for people with good front end knowledge who want to edit the css.

Thanks for all your help, Luke, but I give up.

Best

Katherine

**Comment by lukerague** [comment]
Sorry I couldn't be of more help! Usually this method of customization is straight forward without any hiccups.

**Comment by marcobarbosa** [comment]
FYI I had the same issue as described by @kathep. It is a weird behaviour indeed.

After reading https://github.com/NUKnightLab/TimelineJS/issues/699 and https://github.com/NUKnightLab/TimelineJS/issues/575 I just ended up loading my own custom css after the `<head>`.

Unfortunately that means overwriting a lot of styles but oh well :)
