### ISSUE TITLE
Nav buttons hard to see in skinny mode

### ISSUE THREAD

**Issue by lukerague** [NUKnightLab/TimelineJS#775]
Below the skinny breakpoint, the nav icons switch from the black to white and become hard to see until hovered over, as pointed out in support ticket #1073. This user's website has a very narrow content area, so it i almost always under the breakpoint, so they currently have a sentence above the Timeline explaining how to navigate. This seems like something we should be avoiding.

Maybe we can have use the black versions at the same opacity level, and reserve the white for hover? Since the icon exists beyond the width restriction of the slide's content, this does not cause any legibility issues.

This is what it currently looks like: 
![screenshot 117](https://cloud.githubusercontent.com/assets/7632315/6807989/b3ef8d7e-d21f-11e4-9276-1deea0e36799.png)

This is what it could look like:
![screenshot 115](https://cloud.githubusercontent.com/assets/7632315/6808010/cba45e54-d21f-11e4-9e66-74d98df1a4a2.png)

I meant to push this in a branch, but did not realize I hadn't switched over to the branch before committing and pushing the proposed changes, and I'm getting an error when trying to revert.

I'm failing miserably to commit these changes to a branch and not master, but I'll create a pull request with these changes once I do.

**Comment by zachwise** [comment]
The arrow icons will sit over the content. they are meant to be transparent until hover. This was a carefully thought out design choice.

**Comment by lukerague** [comment]
But... they don't unless the Timeline is ridiculously skinny, and even then the opacity is so low that the icons are fairly non-obtrusive: 
![screenshot 120](https://cloud.githubusercontent.com/assets/7632315/6808770/faaef3cc-d223-11e4-838d-34d2c12bd08f.png)

If you didn't know they were there in the design as is, would you even see them? Because users don't.

**Comment by zachwise** [comment]
Nothing should obstruct content. If users can't figure out by hover then a more radical solution is needed, not one that obstructs content.

**Comment by zachwise** [comment]
I would also add that this is the first time this has come up in 3 years and millions of views, so while not perfect, it still works for most people.

**Comment by lukerague** [comment]
Fair enough
