### ISSUE TITLE
Animation changed

### ISSUE THREAD

**Issue by zachwise** [NUKnightLab/TimelineJS#776]
What happened to the way slides animate? The easing is totally different! Why/when was this changed?!

**Comment by zachwise** [comment]
It looks so robotic now

**Comment by JoeGermuska** [comment]
I don't think anyone changed this intentionally. If you can point to the lines in the code where that is controlled, we can figure out when it happened and how to undo it.

**Comment by zachwise** [comment]
This is the easing definitions:
https://github.com/NUKnightLab/TimelineJS/blob/master/source/js/Core/Library/jQuery/easing.js

Animation ease type is in the config part of each class: https://github.com/NUKnightLab/TimelineJS/blob/master/source/js/VMM.Timeline.js#L135

**Comment by JoeGermuska** [comment]
https://github.com/NUKnightLab/TimelineJS/blame/master/source/js/VMM.Timeline.js#L135 says that that line hasn't changed since 2012.

**Comment by zachwise** [comment]
Yeah, but is the easing file still be compiled?

**Comment by zachwise** [comment]
If not, it defaults to default ease, which is what is happening

**Comment by JoeGermuska** [comment]
Actually, it seems as though the easing is copied into [VMM.Library](https://github.com/NUKnightLab/TimelineJS/blame/master/source/js/Core/Core/VMM.Library.js#L558-L592), also dating back to when that was in StoryJS-Core. 

There's no sign of [.../jQuery/easing.js](https://github.com/NUKnightLab/TimelineJS/blob/master/source/js/Core/Library/jQuery/easing.js) being included in any CodeKit directives.

**Comment by zachwise** [comment]
Are we using a different version of jQuery then? The version I have on my desktop before I handed over control of Timeline animates correctly.

**Comment by zachwise** [comment]
All I'm saying is someone changed something and it doesn't work anymore, and I would like it fixed. The way it animates is not arbitrary.

**Comment by zachwise** [comment]
This seems to be the issue:
https://github.com/NUKnightLab/TimelineJS/pull/681

CSS animation only does not respect easing

**Comment by JoeGermuska** [comment]
fixed in 603b53aaff9cf9e43939caac66c5f8877fbb5fd8
