### ISSUE TITLE
How to know when the TimelineJS initialize complete?

### ISSUE THREAD

**Issue by huang-x-h** [NUKnightLab/TimelineJS#791]
when we use `createStoryJS` method to create timeline

    createStoryJS({
            type: 'timeline',
            width: "100%",
            height: "100%",
            start_at_end: true,
            source: data,
            embed_id: 'timeline-embed'
        });

how can we know when the timeline initialize complete, dose `TimelineJS` have a event like `creationComplete` to fire?

**Comment by JoeGermuska** [comment]
There is not. With [TimelineJS3](/NUKnightLab/TimelineJS3) we are trying to better account for Timeline interacting with outside code. We are scheduled to put it into beta release within the next month.

**Comment by invot** [comment]
is there a way to do this yet?
