### ISSUE TITLE
Timeline timing out drawing info from Google Spreadsheet

### ISSUE THREAD

**Issue by diegoolivas** [NUKnightLab/TimelineJS#812]
It appears that the original timeline is not properly connecting to publish Google Docs spreadsheet. I can't tell whether its a momentary bug, hiccup, or something else altogether. See these examples for the timing out issue:

http://www.lemonde.fr/election-presidentielle-2012/visuel/2012/04/21/chronologie-une-si-longue-campagne-presidentielle_1681661_1471069.html

http://blog.zzounds.com/2015/07/28/musical-timeline-berlin-school-1980-2015/

this issue is appearing on nearly every website that uses the embed code from the site, rather than a wordpress plugin or the compiled version from Github.

Timeline only states: "Still Waiting on Google Docs, Trying Again" all the spreadsheets are fine and published.

**Comment by MvrpcWeb** [comment]
We are having this issue right now. I set our timeline to debug mode, and in the javascript console in Firefox, I got a warning:

`Invalid App Id: Must be a number or numeric string representing the application id.`

followed by an error:

`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://spreadsheets.google.com/feeds/list/1WJKTxrah43cEg5V77RJd8VayJ87cg9-Q0rBuuk92DgI/1/public/values?alt=json. (Reason: CORS request failed).`

Amazingly, we just published the timeline this morning, and it was working fine until a little after 12pm EDT.

**Comment by Ceezerr** [comment]
Similar story here. Publishing three timelines this morning, by the time I got around to testing the third one the "Still Waiting on Google Docs, Tying Again 0" came up

**Comment by JoeGermuska** [comment]
This is a general issue with Google Spreadsheets affecting many applications besides Timeline JS. We anxiously await a solution from Google.

See https://code.google.com/a/google.com/p/apps-api-issues/issues/detail?id=3939 

Closing, as this isn't a bug in TimelineJS.

**Comment by JoeGermuska** [comment]
The Google Spreadsheets issue which was causing TimelineJS problems has been resolved. TimelineJS should behave normally.
