### ISSUE TITLE
Date at the beginning of each month

### ISSUE THREAD

**Issue by Swebask** [NUKnightLab/TimelineJS#820]
The timeline by default, displays the month name at the beginning of a month rather than the month name along with the date 1. For example, it displays Aug. instead of Aug 1. Is there any way to do the latter?

![timelinejs](https://cloud.githubusercontent.com/assets/8941638/11229073/c4ca812a-8d46-11e5-8374-6c21f6cd439c.png)

**Comment by JoeGermuska** [comment]
One might guess that you haven't actually specified the date, but we can't see the data you are using. But this is also better handled through our support desk. Please visit [our support forum](https://knightlab.zendesk.com/home) and post a question or file a support request. Be sure to include a link to the spreadsheet which has the data and, if appropriate, a link to a page which shows the problem in action.
