### ISSUE TITLE
Why so many console logs?

### ISSUE THREAD

**Issue by CarlosAmaral** [NUKnightLab/TimelineJS#831]
This lib throws so many console logs. Any way to disable them?
Thank you!

**Comment by JoeGermuska** [comment]
There is exactly one console.log statement in the compiled TimelineJS code and[ it is behind a test to see if Timeline is in debug mode](http://github.com/NUKnightLab/TimelineJS3/blob/30d10c5463be984080d1f8f1aa2528cf669dfa20/compiled/js/timeline.js#L44-L55).

By default, Timeline should not be running in debug mode. You can control this specifically with the `debug` option, which had accidentally been left off the [options documentation](http://timeline.knightlab.com/docs/options.html) but that has been corrected.

If you are finding differently, please clarify.
