### ISSUE TITLE
Documentation for the examples/ does not detil how to populate ../build/

### ISSUE THREAD

**Issue by paul-hammant** [NUKnightLab/TimelineJS#852]
Thus the examples cannot be run any more.

This TimelineJS (versus v3) is important because it can source timeline data from the same Git repo and is not tied to GoogleDocs, which will be a preference for many end-users.

**Comment by JoeGermuska** [comment]
This version of TimelineJS is no longer supported, and has not been maintained for five years.  

TimelineJS3 is _not_ tied to GoogleDocs. The TimelineJS3 JSON format is described [in this documentation](http://timeline.knightlab.com/docs/json-format.html) and the JS required to instantiate a timeline with that JSON is documented [on this page](http://timeline.knightlab.com/docs/instantiate-a-timeline.html).
